### ISSUE TITLE
Support traditional domains

### ISSUE THREAD

**Issue by seanlinsley** [juanibiapina/zas#11]
A feature of Pow that our team relies on is its ability to respond to traditional TLDs like `.com`, primarily so that we can support Google OAuth in development (which requires a valid TLD).

IIRC Pow doesn't actually support DNS lookup in this scenario, so we have the `dev` subdomain of our website pointing to localhost.

**Comment by juanibiapina** [comment]
I don't understand what you need exactly. Do you need a configuration to respond to other domains like ".com", ".local", etc?

**Comment by seanlinsley** [comment]
Yes. The setting in Pow is `POW_EXT_DOMAINS`

http://pow.cx/manual.html#section_3.1

> If you want Pow to serve apps under additional top-level domains, but not serve DNS queries for those domains, use the `POW_EXT_DOMAINS` variable. Entries in `POW_EXT_DOMAINS` will not be configured with the system resolver, so you must make sure they point to your computer by other means.

**Comment by juanibiapina** [comment]
Now I got it. This might be a good idea.

**Comment by juanibiapina** [comment]
@seanlinsley zas doesn't actually check the TLD, so this should work already.

**Comment by juanibiapina** [comment]
I should probably add documentation on how to point directly at the zas http server.

**Comment by juanibiapina** [comment]
I just tested and this works.
