### ISSUE TITLE
Support .local TLD?

### ISSUE THREAD

**Issue by gmsecrieru** [juanibiapina/zas#26]
Hi,

Thanks for your efforts, very much appreciated! 

I have forked the project and made a few changes in order to support `.local` TLD since [Chrome is now forcing HTTPS for .dev domains](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/). 

Would you be interested in this change? I can try to put together a PR -- I don't have much Rust experience but managed to edit the project and make it work.

Thanks again!

**Comment by juanibiapina** [comment]
If you're able to use different TLDs in your project, why not just use `.localhost`? That should automatically map to 127.0.0.1, although I don't know what the exact rules are.

**Comment by gmsecrieru** [comment]
I see `.local` as a convenient/shorthand version of `.localhost`. However, I don't think there is an automatic mapping between 127.0.0.1 and this TLD.

**Comment by juanibiapina** [comment]
`.localhost` is designed to work with 127.0.0.1, while `.local` has a set of different semantics which, although could be used here, might eventually cause confusion. It's not worth changing it in order to save 4 characters.

Using `.localhost` we eliminate the need for a DNS server altogether.

References:
- https://en.wikipedia.org/wiki/.local
- https://en.wikipedia.org/wiki/.localhost
- https://tools.ietf.org/html/rfc6762

**Comment by juanibiapina** [comment]
@gmsecrieru I've released a new version of zas where the DNS server responds to any TLDs. To test it, get version 0.21.0 and manually create a file called `/etc/resolver/tld` with the TLD you'd like to use. I plan on making it more generic later, but this should be enough to start using and testing.

**Comment by gmsecrieru** [comment]
@juanibiapina that's great! I've been running my own fork but it is not very flexible as I still needed to update `/etc/hosts` due to my choice for `.local` -- I believe that is related to what you explained in previous comments -- not a TLD expert over here :)

Anyways, I will give it a shot as soon as I am able. Thanks for getting back to me, very much appreciated.
